---
version: '3.8'
name: client
services:
  app:
    container_name: client.app
    image: 'node:22-slim'
    command: /bin/bash -c "npm run dev"
    working_dir: /data
    volumes:
      - ${PWD}:/data:delegated
    ports:
      - '5173:5173'
